name: firebase_messenger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  heroicons: ^0.11.0
  file_picker: ^10.3.7
  path_provider: ^2.1.5
  http: ^1.6.0
  shared_preferences: ^2.5.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo_512.png

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: assets/logo_1500.png
  adaptive_icon_background: assets/logo_1500.png
  adaptive_icon_foreground: assets/logo_1500.png
  min_sdk_android: 28