name: fire_message
description: "Fire Message"
publish_to: 'none'
version: 1.1.0+12

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  heroicons: ^0.11.0
  file_picker: ^10.3.7
  path_provider: ^2.1.5
  http: ^1.6.0
  shared_preferences: ^2.5.4
  flutter_launcher_icons: ^0.14.4
  webview_flutter: ^4.13.0
  google_fonts: ^6.3.3
  googleapis_auth: ^2.0.0
  purchases_flutter: ^9.10.0
  action_slider: ^0.7.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/logo_512.png
    - .env

flutter_intl:
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: assets/logo_512.png
  adaptive_icon_background: assets/logo_512.png
  adaptive_icon_foreground: assets/logo_512.png
  min_sdk_android: 28